from sqlalchemy import String, Date, DateTime, ForeignKey
from sqlalchemy.dialects.postgresql import UUID, ENUM
from sqlalchemy.orm import Mapped, mapped_column, relationship
from datetime import datetime, date, timezone
import uuid

from app.core.database import Base


class MaintenanceRecommendation(Base):
    """
    An actionable maintenance suggestion generated by the AI service.
    
    Links a prediction (AI finding) to a concrete action.
    Example:
      Prediction: "Anomaly detected — CPU consistently above 90%"
      → Recommendation: "Investigate high CPU usage. Check for runaway
        processes or consider hardware upgrade."
    
    Lifecycle:
      pending → in_progress → completed
      (or dismissed if admin decides it's not needed)
    """
    __tablename__ = "maintenance_recommendations"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    device_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("devices.id", ondelete="CASCADE"), nullable=False
    )
    prediction_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("predictions.id", ondelete="SET NULL")
    )

    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str] = mapped_column(String, nullable=False)
    priority: Mapped[str] = mapped_column(
        ENUM("low", "medium", "high", "urgent", name="recommendation_priority"),
        default="medium",
    )
    category: Mapped[str] = mapped_column(
        ENUM("hardware", "software", "security", "performance", "storage", "network", name="recommendation_category"),
        nullable=False,
    )

    # Lifecycle
    status: Mapped[str] = mapped_column(
        ENUM("pending", "in_progress", "completed", "dismissed", name="recommendation_status"),
        default="pending",
    )
    assigned_to: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL")
    )
    due_date: Mapped[date | None] = mapped_column(Date)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )

    # Relationships
    device = relationship("Device", back_populates="recommendations")
    prediction = relationship("Prediction", back_populates="recommendations")
    assigned_user = relationship("User", back_populates="assigned_recommendations")
